apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app"
  annotations:
    argocd/app-name: my-quarkus-app-dev
    backstage.io/kubernetes-id: my-quarkus-app
    github.com/project-slug: janus-platforms-test/my-quarkus-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-xc2n2.xc2n2.sandbox1014.opentlc.com/#https://github.com/janus-platforms-test/my-quarkus-app?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-xc2n2.xc2n2.sandbox1014.opentlc.com/#https://github.com/janus-platforms-test/my-quarkus-app?che-editor=che-incubator/che-idea/next&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "mattheh"